### ISSUE TITLE
Request for invite as collaborator

### ISSUE THREAD

**Issue by seanes** [Altinn/altinn-components#1]
### Description

As frontend developer for Team Arbeidsflate I would like to be invited as collaborator with write access in order to be able to contribute code to this repository, cf. https://github.com/Altinn/altinn-decision-log/issues/12., as a deemed maintainer/team member.

**Comment by altinnadmin** [comment]
You've now been invited to @Altinn/team-dialogporten along with the rest of the team from the Digdir org.
